### ISSUE TITLE
Guard libcryptsetup calls with a mutex internally

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/libcryptsetup-rs#120]
@mulkieran Currently, we're doing this in stratisd but we may have more control over this in the `Drop` implementations for example and protect other users of libcryptsetup-rs if we do this in the library instead. It would also simplify the code for stratisd. What do you think? Do you want me to investigate this further?

**Comment by mulkieran** [comment]
@jbaublitz If you think this would be more generally useful in the library than in stratisd, and that it might also be implemented more cleanly, you should definitely give it a try.
