### ISSUE TITLE
Consider panicking if safety cannot be ensured

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/libcryptsetup-rs#151]
I'm working on #139 now and the main problem that we bumped into with our mutex feature is that not all methods in libcryptsetup return an error so it is not possible to just return an error in the macro. The same applies for this issue. For the mutex feature, we opted to log a warning message, but I'm currently debating whether it would be better to just panic.

My reasoning for this is primarily based on the following:
* It is not impossible for libcryptsetup to cause corruption if the mutually exclusive access can't be enforced and logging might not be enough to catch a user's attention particularly for something like a background process. Rather than allow the process to keep running and potentially cause corruption, it may be better to simply panic.
* The case where panicking would occur for failure of the mutex acquisition is really only where a thread has already panicked. If there's already a panic happening in the code using libcryptsetup-rs, I feel like it is not unreasonable for us to panic in response.
* The case where panicking would occur for enforcing single threaded actions without the `mutex` feature seems very acceptable as this is a programmer error for the user of our library, and they absolutely need to either enable the `mutex` feature or enforce a single-threaded model. I don't think we should allow users to stumble on corruption errors if they do not have logging enabled.

@mulkieran What are your thoughts?

@DemiMarie Do you have a strong preference either way?

**Comment by DemiMarie** [comment]
@jbaublitz My preference would be to fix this in upstream libcryptsetup, unless there is a fundamental reason (bad kernel APIs?) why it cannot be.  Otherwise, I think the mutex feature should be the default; I imagine that virtually all operations involving libcryptsetup are expensive enough that the performance overhead should be negligible.

**Comment by mulkieran** [comment]
@jbaublitz It seems to me that your arguments for panicking are good. Given that, the best thing to do is document emphatically and also test, if possible.

**Comment by jbaublitz** [comment]
@mulkieran Okay yes, I plan to add a test for both if I'm able. I will definitely be able to test panicking by calling from multiple threads without the `mutex` feature enabled.
