### ISSUE TITLE
Broken link to docs in readme

### ISSUE THREAD

**Issue by curtisforrester** [stratis-storage/libcryptsetup-rs#194]
In the "README.md" the section "API Documentation" has a broken link for "here".

```
[here](https://stratis-storage.github.io/libcryptsetup-rs/doc/libcryptsetup_rs/index.html)
```

I looked here - and even there, but couldn't find it. Admittedly, I didn't look high and low for it. 😁

**Comment by mulkieran** [comment]
Thanks for spotting that, I think you should be looking here now: https://docs.rs/libcryptsetup-rs/0.4.4/libcryptsetup_rs/. (There was a technical difficulty w/ building the docs on crates.io once).
