### ISSUE TITLE
Unexposed safe free function in libcryptsetup

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/libcryptsetup-rs#2]
See upstream: https://gitlab.com/cryptsetup/cryptsetup/merge_requests/63. This should be fixed in next libcryptsetup release.

**Comment by mulkieran** [comment]
@jbaublitz: Is the new version of libcryptsetup available at all in a release? As time passes we might want to consider removing the inlined code here (upstream), and patching the downstream release instead. It's more work, but it would put the work where the problem is.

**Comment by jbaublitz** [comment]
It looks like there's a release candidate available. Once it's officially released, I plan to do this as soon as possible.

**Comment by mulkieran** [comment]
> It looks like there's a release candidate available. Once it's officially released, I plan to do this as soon as possible.

Just noting that we talked this over and it seemed like extending the build script to check the version of libcryptsetup available, and taking action accordingly, would be the most robust plan. Eventually, this extra bit in the build script could be removed.

**Comment by jbaublitz** [comment]
I'm working on a PR now to add the feature flagging by version. I'll be putting together some Travis tests soon to test on 2.2 and 2.3 so we can make sure it works in both cases.

**Comment by mulkieran** [comment]
Great!

**Comment by jbaublitz** [comment]
I think we can close this now that cryptsetup 2.3 has officially been released on Fedora and #23 has been merged.
