### ISSUE TITLE
Document that format() requires key size in units of bytes

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/libcryptsetup-rs#28]
`crypt_format` in libcryptsetup requires the key size in bytes. I would like to allow either bits or bytes and to have the user explicitly specify which using an enum like the following:

```
pub enum KeysizeUnits {
    Bits(usize),
    Bytes(usize),
}
```

This may help avoid confusion around the pattern that I've seen of `512 / 8` or `256 / 8` for this parameter. We can do the calculation for bits and return `EINVAL` if not divisible by 8 and pass through number of bytes unaltered.

**Comment by jbaublitz** [comment]
This may not make a lot of sense after working on #35. I would much prefer having a `Deref` implementation for types signifying units and with an enum, it's a bit harder to specify that the `usize` value in `Bits(usize)` must always be divisible by 8. Furthermore, we can't stop a user from constructing the variant `KeysizeUnits::Bits(7)`. This may simply be an instance of documenting that the input must be in bytes.

**Comment by mulkieran** [comment]
Feel free to close.
