### ISSUE TITLE
Breaking change released as 0.7.1

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/libcryptsetup-rs#297]
#292 was released as 0.7.1 but while I believe it is a design improvement, it is technically a breaking change.

@wcs1only After digging a bit deeper, you were passing in the wrong struct. `&inner` is public so if you took a reference in the caller to `&inner`. We never actually made an assumption about layout but left it up to the user to correctly take the reference of the inner field. As such, anyone using the API correctly would actually have their code stop working as of 0.7.1.

The reason I think this API that you proposed is an improvement is mainly because I'm the only person who understood it, and that's not good API design. It wasn't evident from the design how to interact with it. It seems like everyone who used that API did the exact same thing you did and thus introduced the same bug you did. I'd like the compiler to catch this in the future which I think is a good argument for accepting this.

I want this change, but we may need to yank it and rerelease as 0.8.0 just in case anyone used it as intended somewhere.

**Comment by wcs1only** [comment]
Be sure you fix https://github.com/stratis-storage/stratisd/blob/60d007b13414b0253714c557bf02cb4c9a525989/src/engine/strat_engine/backstore/crypt/handle.rs#L335

As well. I don't believe it is using .inner, and that was the code I was trying not to break with this change.

**Comment by wcs1only** [comment]
Deleted my previous comment, because I misinterpreted what you were saying. You're saying you're bumping 0.8.0 to reflect the fact that this is a breaking change, but still accepting the change.
